const express=require('express');
const router=express.Router();
const userController=require('../controllers/userController');
const fileUpload = require('express-fileUpload');
router.get('/',userController.view);
router.post('/',userController.find);
router.post('/login',userController.login);
router.get('/addemployee',userController.form);
router.post('/addemployee',userController.create);
router.get('/editemployee/:emp_id',userController.edit);
router.post('/editemployee/:emp_id',userController.update);
router.get('/deleteemployee/:emp_id',userController.delete);
router.get('/viewemployee/:emp_id',userController.viewEmployee);
router.get('/viewDepartments',userController.viewDepartments);
router.get('/viewProjects',userController.viewProjects);
router.get('/viewDepartment/:dept_id',userController.singleDept);
router.get('/signup',userController.signup);
router.post('/signupSubmit',userController.signupSubmit);
router.get('/viewprojectsingle/:project_id',userController.singleProject);
module.exports=router;